### ISSUE TITLE
problem button in 'about page'

### ISSUE THREAD

**Issue by briceterdjman** [we-do-data/IFS_AFD-ACES-dev#11]
quand on ouvre pour la première fois l'app, dans la page about, le bouton cards en bas est caché, on clique sur la croix mécaniquement et on revient en arrière. Je pense qu'il faut que la croix permette d'aller sur la carte

**Comment by JulienParis** [comment]
@briceterdjman tu pourrais mettre un screenshot du bug stp ?

**Comment by JulienParis** [comment]
comportement du bouton changé : 
- si 1ere visite => renvoit vers /cards
- si pas 1ere visite => renvoit vers page précédente

**Comment by JulienParis** [comment]
a priori l'issue peut être fermée si tu confirmes et que tu n'as pas d'autre remarque dessus

**Comment by clementWedodata** [comment]
Vu ensemble, je ferme l'issue.
