### ISSUE TITLE
prepare the production's spreadsheet

### ISSUE THREAD

**Issue by JulienParis** [we-do-data/IFS_AFD-ACES-dev#12]

**Comment by JulienParis** [comment]
@briceterdjman 
le GSheet expurgé pour la prod est là : https://docs.google.com/spreadsheets/d/1JYvnZ8sYg9n2Rmfty8xRX7qQZCwVLl7CHoewxaBVbDA/edit#gid=0

Je l'ai testé en local, il me reste juste à changer quelques variables d'environnement pour la vue en prod (et du coup j'en ai aussi profité pour corriger un bug concernant la visibilité de la dernière carte du jeu complet, qui sautait auparavant)

**Comment by JulienParis** [comment]
l'url de preprod avec ces données est là :

**Comment by briceterdjman** [comment]
OK merci. Peuxt-on se passer des onglets tags-correspondance et data-types histoire de simplifier encore plus pour le client ? Sinon, peux-tu enlever tout le superflu qu'il reste (surement des lignes ou des colonnes. 
Est-ce que la colonne 'author' dans le spreadsheet des questions est-elle nécessaire ?

**Comment by JulienParis** [comment]
Pour encore plus de lisibilité pour le client je me disais qu'on peut tout à fait ne garder que la première feuille/onglet du document "client", et garder les autres onglets dans un autre document GSheet . Je fais ça ce matin...

**Comment by JulienParis** [comment]
en passant j'ai ajouté un petit 'disabled' du bouton `find more` des cartes quand il n'y a pas de ressource à afficher

**Comment by JulienParis** [comment]
théoriquement on devrait pouvoir effacer les onglets superflus maintenant

**Comment by JulienParis** [comment]
@briceterdjman fais-moi signe sur slack quand tu voudras qu'on fasse le test (je préfère car ça impacte directement la prod / preprod)
