### ISSUE TITLE
card's footer ("like" btn) don't have to move when "find more" is clicked

### ISSUE THREAD

**Issue by JulienParis** [we-do-data/IFS_AFD-ACES-dev#15]

**Comment by JulienParis** [comment]
@clementWedodata j'ai fait un fix temporaire de cette issue... Pas réussi pour le moment à trouver une animation convaincante, pour le moment juste un switch entre contenu et ressources

**Comment by clementWedodata** [comment]
@JulienParis 

ok, ça me va ainsi.
