### ISSUE TITLE
blur bug in chrome on cards after scale

### ISSUE THREAD

**Issue by JulienParis** [we-do-data/IFS_AFD-ACES-dev#16]
on Chrome and Safari also

**Comment by JulienParis** [comment]
@clementWedodata if you got some docs more on the matter : 
https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome

**Comment by JulienParis** [comment]
![capture_d___e__cran_2019-07-25_a___16 51 43](https://user-images.githubusercontent.com/21986727/61885349-fa407d00-aefd-11e9-8240-658a4ab902fa.png)

**Comment by clementWedodata** [comment]
Le problème semble réglé sur Chrome et Safari
