### ISSUE TITLE
Taille du logo - écran choose your language

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#19]
Mobile > 
Le logo est trop gros et il manque le titre de la webapp. (Play with transitions)

**Comment by JulienParis** [comment]
pense bien à me préciser si c'est sur mobile / sur desktop / les 2. Il y a un switch sur la taille des logos qui prend en compte la hauteur de l'écran

**Comment by JulienParis** [comment]
ajouté titre de l'app

hauteurs de logo proposées : 
- 50px sur mobile
- 70px sur desk

**Comment by JulienParis** [comment]
@clementWedodata pour check

**Comment by clementWedodata** [comment]
OK, je ferme
