### ISSUE TITLE
Nom de la webapp - Français/Anglais

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#21]
On va garder le même nom pour la webapp, que ça soit en Français ou en Anglais
Play With Transitions

**Comment by JulienParis** [comment]
@clementWedodata @briceterdjman 
j'ai changé le titre qui apparaît dans l'onglet dans le code ( nuxt.config => https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/08c6451ad9ded2050ce7afa7df10cec088f3726f )
Il me reste juste à changer la variable d'environnement dans netlify pour que ce soit visible sur le site de preprod

**Comment by JulienParis** [comment]
ah j'ai aussi ajouté le favicon à l'app : commit https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/07ca6ad6433da6e9210bf2377e9da7582d319653

**Comment by JulienParis** [comment]
normalement le nom de l'app + le favicon apparaissent bien dans l'onglet maintenant :

**Comment by clementWedodata** [comment]
OK pour le favicon+title dans l'onglet. 

Par contre on conserva le nom "Play With Transitions", que ça soit sur la version EN ou FR de l'app.

**Comment by JulienParis** [comment]
ah ok j'avais pas tilté, je l'avais mis en EN en titre dans l'onglet mais traduit partout ailleurs. Je corrigerai ça

**Comment by JulienParis** [comment]
@clementWedodata pour check (notamment si le jeu avec les espaces pour écrire `. cards` te semble assez joli

**Comment by clementWedodata** [comment]
@JulienParis 

ca me va mais en ajoutant le .cards on créer un soucis sur mobile, le texte passe à la ligne avec ce nouveau titre plus long. Je te propose une règle entre 380 et 430px > font size 18px / letter spacing 0.10em et en dessous de 380px, font-size 16px.

**Comment by clementWedodata** [comment]
@JulienParis 

ok, visiblement tu l'as réglé.

**Comment by JulienParis** [comment]
@clementWedodata pour check

**Comment by clementWedodata** [comment]
Yes, bon pour moi.
