### ISSUE TITLE
Style bouton "get a card"

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#23]
Desktop / mobile > 
Le bouton ne devrait pas avoir de box-shadow

**Comment by JulienParis** [comment]
réglé...

Note pour plus tard : bouton défini comme `flat` dans vuetify mais toujours avec box-shadow... chelou. pe dû à l'overwrite du CSS custom `btn-gradient`

**Comment by JulienParis** [comment]
@clementWedodata un fois confirmé de ton côté on pourra fermer l'issue

**Comment by clementWedodata** [comment]
Yes, c'est bon, je close.
