### ISSUE TITLE
Animation transition cards

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#24]
Desktop / mobile > 

Lorsqu'on passe à la carte suivante, le texte de la carte suivante saute des lignes en fin de transition, ça créer un effet non souhaitable. 
Voici une capture vidéo du soucis : 
https://www.dropbox.com/s/f80zfw0d5g5sznu/recettage-afd-playwithtransition-01.mov?dl=0

**Comment by JulienParis** [comment]
yep, il faudra trouver une manière de régler ça en août à mon avis, avec toutes les tailles d'écran sous la main... le truc c'est qu'il y a un scale entre les cartes de dessus et de dessous...
tiens en fait ça me donne une idée conne, peut-être faudrait-il juste ajouter le même ratio de scale à la typo entre les cartes de dessus et de dessous...

**Comment by JulienParis** [comment]
@clementWedodata ça normalement avec l'effet de simple translation des cartes c'est réglé (et ça devrait pas le refaire si on opte pour une rotation en plus ...). normalement on devrait pouvoir clore

**Comment by clementWedodata** [comment]
Yes, je ferme.
