### ISSUE TITLE
Animation de transition - next card - vitesse

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#25]
Desktop / mobile >
Régler la vitesse d'animation de la transition lorsqu'on clique sur le bouton next, il faudrait que ça soit plus lent.

**Comment by JulienParis** [comment]
j'ai un peu augmenté le temps de la transition : avant c'était .5s, maintenant c'est .8s
commit => https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/5e20d3d1f82f9f54ca2341e549bb60de38042a67

@clementWedodata comme d'hab je te laisse checker avant de clore l'issue

**Comment by clementWedodata** [comment]
Yes, c'est nickel, ça match mieux avec la vitesse quelles ont lorsqu'on swap.
