### ISSUE TITLE
Animation transition - find more

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#26]
Desktop / mobile tous navigateurs >

la transition lorsqu'on clique sur Find more n'est pas très fluide et laisse apparaître le contenu en overflow en dehors de la carte. Au clique sur le bouton, l'ensemble _bouton find more+label+bouton fav_ se décale vers le bas puis apparaît tout en haut. La phrase disparaît instantanément. 

Pourrait-on : 
- effacer la phrase en fade out en jouant sur l'opacité 1>0 
- faire remonter le bloc "footer"(bouton find more+fav) avec une transition sans saccade 
- faire remonter les liens avec la même animation de transition. 
- tout ça moins rapidement avec un jolie ease-in-out

**Comment by JulienParis** [comment]
yep, en août j'aurai fait une proposition là-dessus à mon avis

**Comment by clementWedodata** [comment]
je ferme l'issue qui fait doublons avec un autre ticket.
