### ISSUE TITLE
Taille de typo générale des cards 

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#27]
En l'état, la taille moyenne d'affichage des citations est un peu petite, il faudrait pousser ton réglage pour augmenter la taille de typo de manière générale. Et ajouter un letter-spacing de 0.03em histoire de faire respirer cette typo bien grasse :)

<img width="450" alt="recettage-afd-playwithtransition-03A" src="https://user-images.githubusercontent.com/52534300/62113067-384df000-b2b4-11e9-8c78-4e80f17ba95d.png">
<img width="437" alt="recettage-afd-playwithtransition-03B" src="https://user-images.githubusercontent.com/52534300/62113068-384df000-b2b4-11e9-9791-5e26495cf796.png">

**Comment by JulienParis** [comment]
Je viens d'ajouter un `letter-spacing` de `.01em` pour le moment, autrement ça sortait super bizarre 
<img width="396" alt="Capture d’écran 2019-07-31 à 12 33 41" src="https://user-images.githubusercontent.com/21986727/62205385-9ef40c00-b38f-11e9-8f9c-1a7804fa9e55.png">
<img width="398" alt="Capture d’écran 2019-07-31 à 12 33 57" src="https://user-images.githubusercontent.com/21986727/62205390-a0253900-b38f-11e9-9c01-a7dc90031c5d.png">

Sinon ça va être un peu du tuning à faire ensemble vu que la taille de la police change en fonction : 
- de la taille de l'écran
- du device
- de la longueur de la citation...

Pas mal de variables donc, je te propose qu'on fasse ça en août

**Comment by clementWedodata** [comment]
Yes, ça me va pour le letter-spacing. 
On finira de caler ça ensemble, ça marche.

**Comment by JulienParis** [comment]
@clementWedodata voir ce que tu en dis pour check

**Comment by clementWedodata** [comment]
@JulienParis 

c'est un peu mieux, j'ai encore des phrases qui s'affichent petite (sur mon mobile en tout cas), alors qu'on aurait la place de les écrires plus grosses, sur 3, 4 lignes. ex : _Le .rtf c'est un peu le .csv du .doc_
