### ISSUE TITLE
position bouton "get a card"

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#28]
Sur iPhone 10, Safari et Chrome, le bouton Get a Card se positionne sous la barre de navigation basse, on passe donc à côté. 
![recettage-afd-playwithtransition-04](https://user-images.githubusercontent.com/52534300/62114861-c2e41e80-b2b7-11e9-917e-e514318e2ac3.png)

**Comment by JulienParis** [comment]
je pense avoir réglé ça, à confirmer sur tous les devices

**Comment by JulienParis** [comment]
bouton enlevé suite à discussion avec Brice @clementWedodata

**Comment by clementWedodata** [comment]
Ok, je ferme l'issue.
