### ISSUE TITLE
Animation transition cards - point d'aimantation de sortie d'une card

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#29]
Desktop > 
Sur desktop le point d'aimantation de sortie d'une card n'est pas assez en dehors du screen, si on peut le repousser ça serait pas mal. 

https://www.dropbox.com/s/557oeaxyu1vd8b2/recettage-afd-playwithtransition-05.mov?dl=0

**Comment by JulienParis** [comment]
treshold de disparition de la carte augmenté => commit https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/de129195aa014d11fe76a6387bf2a911ae434ee6

**Comment by JulienParis** [comment]
@clementWedodata je te laisse checker pour clore l'issue

**Comment by clementWedodata** [comment]
Yes, c'est mieux ainsi.
