### ISSUE TITLE
Difficulté du swipe

### ISSUE THREAD

**Issue by briceterdjman** [we-do-data/IFS_AFD-ACES-dev#31]
Après qq tests utilisateurs, quand on swipe les cartes, il faut dragger la card quasiment jusqu'au bord de l'écran pour que la carte swipe. Il faudrait que le swipe s'active plus facilement.

**Comment by clementWedodata** [comment]
@JulienParis 

ok, ça semble mieux, je ne sais pas si tu as fait quelque chose.
