### ISSUE TITLE
sur mobile, faire annuler l'état hover sur un bouton après le clic

### ISSUE THREAD

**Issue by briceterdjman** [we-do-data/IFS_AFD-ACES-dev#32]

**Comment by JulienParis** [comment]
@clementWedodata j'ai gardé l'effet hover sur desktop mais désactivé quand on est sur mobile... il y a apparemment un bug dans le framework qui cause ça (ref https://github.com/vuetifyjs/vuetify/issues/2178)

**Comment by clementWedodata** [comment]
Ok, c'est bon pour nous. Merci
