### ISSUE TITLE
Export image : le logo est étiré

### ISSUE THREAD

**Issue by briceterdjman** [we-do-data/IFS_AFD-ACES-dev#33]

**Comment by JulienParis** [comment]
@briceterdjman @clementWedodata chez moi (desk et mobile) j'ai plus ce souci... c'est bon de votre côté ?

**Comment by clementWedodata** [comment]
@JulienParis 

voici le rendu d'un export sur Chrome desktop, donc on a encore le soucis. 
Pareil sur Mobile, logo toujours étiré.
![afd_export](https://user-images.githubusercontent.com/52534300/64003647-f90dfb80-cb0c-11e9-82d2-9093b5f90017.jpg)

**Comment by JulienParis** [comment]
c'est chelou quand même ces effets...

**Comment by clementWedodata** [comment]
@JulienParis 

voici le rendu d'un export sur Firefox desktop (screenshot de l'image ouverte dans aperçu pour te rendre compte du soucis sur FF). 
<img width="701" alt="Capture d’écran 2019-08-30 à 10 02 29" src="https://user-images.githubusercontent.com/52534300/64003797-4be7b300-cb0d-11e9-92ba-cffdd19544a8.png">

**Comment by JulienParis** [comment]
@clementWedodata je suis en train de regarder ça, je te ping dès que j'aurai ajouté les modifs. J'ai déjà tenté d'imposer la couleur `white` au texte... à vérifier sur ton android donc 

en attendant pour tenter de gérer cette histoire de logo étiré tu pourrais me sortir un .png du logo `logo-afd-white.svg` ? (je me dis que c'est pe le svg qui est bizarrement interprété dans le blob...)

**Comment by clementWedodata** [comment]
@JulienParis 

voici le logo png transparent en version @2x 
<img width="97" alt="logo-afd-white@2x" src="https://user-images.githubusercontent.com/52534300/64007440-7d17b180-cb14-11e9-8317-0297bd045701.png">

**Comment by JulienParis** [comment]
bon je pense avoir réglé ce problème, ça devait être un padding de trop sur le bloc logo (je n'ai laissé que du margin, ca évite de déformer apparemment sur des petits écrans / en mode export)... et après répercussions du au switch sur ce bloc en mode 'export'... @clementWedodata @briceterdjman pour check donc

**Comment by JulienParis** [comment]
et merci pour le .png @clementWedodata

**Comment by clementWedodata** [comment]
@JulienParis 

c'est ok sur les différents navigateurs, desk et mobile. 

Merci
