### ISSUE TITLE
Mobile : Boutons à propos et crédits sont toujours masqués par la bottom bar du nav 

### ISSUE THREAD

**Issue by briceterdjman** [we-do-data/IFS_AFD-ACES-dev#35]

**Comment by JulienParis** [comment]
@clementWedodata pour check...

test fix with commit https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/615e38836691f815a68b281d7137c9d628a6870a

**Comment by clementWedodata** [comment]
@JulienParis 
sur mon mobile c'est bon, je laisse Brice regarder sur son iPhone. 

Merci

**Comment by JulienParis** [comment]
en attente du retour de @briceterdjman pour clore ce point
