### ISSUE TITLE
Menu : respecter le styleguide pour la couleur de typo des pages en gris car sinon pas lisible

### ISSUE THREAD

**Issue by briceterdjman** [we-do-data/IFS_AFD-ACES-dev#36]

**Comment by JulienParis** [comment]
@clementWedodata il me semblait avoir bien mis la bonne couleur sur les titres désactivés du menu (le gris `#6a6192`) sur fond violet... La seule chose qui différait était le 'bold' appliqué uniquement sur le lien actif (current page). Correction comme suit ... 

ma propale donc : 

fond blanc : en bold sur le lien actif uniquement,
fond violet (cartes) : en bold sur tous les liens, couleur `#6a6192` sur les liens non actifs
tous les fonds : letter-spacing de .1em pour mieux coller au styleguide (.05em semblait très collé par rapport au styleguide)

**Comment by clementWedodata** [comment]
@JulienParis 

voici ce que je proposais dans le styleguide par rapport au menu. Le page active doit avoir un background #6a6192. Tous les textes sont en blanc hormis la langue non active. **Ça évite un problème d'accessibilité.** Le hover est très bien comme tu l'as fais. 
Pour le letter spacing, pas de problème on adapte pour être au plus proche de la maquette. 

Merci
![panelmenu](https://user-images.githubusercontent.com/52534300/63933654-f69e9980-ca59-11e9-9d6e-cdfb43ab1cb9.png)

**Comment by JulienParis** [comment]
ok je viens d'ajouter un fix pour check... commit https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/d72ee8ff5cb782d7bc0646ff62d232492f281d5f

**Comment by clementWedodata** [comment]
@JulienParis 

tu as pushé ? je ne vois pas de différence. 
D'autre part le filet qui sépare "favorite aces" et "About" est cliquable et recharge la webapp. Étrange.

**Comment by JulienParis** [comment]
oui oui c'est pushé et maintenant repushé avec le filet désactivé

**Comment by clementWedodata** [comment]
@JulienParis 

hum, merci pour l'update. Par contre, peut être qu'on arrive pas à se comprendre sur ce menu, mais voici un screenshot qui met en vis à vis ma proposition (à gauche) et ton inté (à droite).
Du coup, sur ta proposition, les textes des liens pour lesquels nous ne sommes pas sur la page active ne sont pas accessible. Le contraste ne passe pas le RG2A, donc il faut écrire en blanc comme sur ma proposition. 
Enfin, dans mon idée et sur le styleguide, je simule l'état d'une page active avec le rectangle violet clair sous le lien (Homepage). 

Pour clore le ticket, il faudrait que le bouton close soit dans un rond blanc pour être cohérent avec les autres boutons et revoir le dégradé sous le panel pour lequel je t'avais mis le lien vers le bon code du gradient. 

Je te remercie, je reste dispo s'il reste des zones d'ombres pour toi. 
![Capture d’écran 2019-08-29 à 15 20 07](https://user-images.githubusercontent.com/52534300/63944209-6d935c80-ca71-11e9-95a6-3222154dab58.png)

**Comment by JulienParis** [comment]
ok j'ai fait des modifs dessus... pas encore au clair sur l'ombré et le calque gris qui s'applique par défaut en-dessous

**Comment by clementWedodata** [comment]
@JulienParis 

ok ça me parait pas mal. 
- Qu'est ce qui n'est pas clair pour le bandeau "gris" ? 
- Concernant l'ombre du menu, j'avais imaginé utiliser un gradient en background d'une div placé en before ou after de ton panel menu pour arriver au même rendu que sur la maquette. Ce n'est peut être pas la bonne solution en terme de code, donc voici un box shadow qui se rapproche du rendu : 
-webkit-box-shadow: -20px 0 50px 0 rgba(27,20,59,0.6);
box-shadow: -20px 0 50px 0 rgba(27,20,59,0.6);

**Comment by JulienParis** [comment]
oui entre-temps j'ai résolu cette histoire de fond gris... je regarde pour le box shadow

**Comment by JulienParis** [comment]
@clementWedodata normalement on devrait pouvoir clore ici... pour check

**Comment by clementWedodata** [comment]
Ok impec pour moi. Merci
