### ISSUE TITLE
Bug : le swipe est désactivé quand on a scrollé la page about

### ISSUE THREAD

**Issue by briceterdjman** [we-do-data/IFS_AFD-ACES-dev#37]

**Comment by JulienParis** [comment]
uniquement sur mobile et uniquement sur iphone

**Comment by JulienParis** [comment]
c'est un bug chelou ce truc quand même...

**Comment by JulienParis** [comment]
bon je pense avoir réussi à bloquer le scroll sur le canevas général des pages d'intro / about / credits / favorites pour prévenir ce bug sur IOS... @briceterdjman si tu peux tester de ton côté ?
