### ISSUE TITLE
contenus d'une page(?) explicative sur utilisation des cookies

### ISSUE THREAD

**Issue by JulienParis** [we-do-data/IFS_AFD-ACES-dev#42]

**Comment by JulienParis** [comment]
@briceterdjman pour les contenus (phrases en/fr)
@clementWedodata pour la propale designée

**Comment by clementWedodata** [comment]
@JulienParis 
On va faire simple, on cale la phrase dans le banner de cookie. Au clique sur "learn more" tu augmentes la hauteur du banner et on affiche la phrase qui explique le tracking. 

phrase FR : 
playwithtransitions.cards enregistre des informations dans les cookies des utilisateurs pour stocker les cartes favorites et améliorer l’usage de l’application.

phrase EN : 
playwithtransitions.cards records information in users’ cookies to store favorite cards and improve the use of the application.
![recettage-afd-playwithtransition-12](https://user-images.githubusercontent.com/52534300/63929126-301ed700-ca51-11e9-8664-d8f74172229a.png)

**Comment by JulienParis** [comment]
par contre on peut plus "refermer" les infos vu comme ça

**Comment by clementWedodata** [comment]
@JulienParis // @briceterdjman 

mais en fait on ne propose pas à l'utilisateur de dire non. Donc de toute façon c'est purement à titre indicatif, le "got it" n'active rien de particulier ? Par défaut on pose un cookie pour le store des favorites et on le track avec des analytics, qu'il clique sur Got It ou non ?

Si on allait au bout du truc il faudrait un bouton "ne me track pas et ne pose aucun cookie" + "got it" ?

**Comment by JulienParis** [comment]
@clementWedodata effectivement c'est encore un peu un faux choix... Là par défaut les cookies sont utilisés que l'utilisateur clique sur "got it" ou pas

**Comment by JulienParis** [comment]
j'ai fait qqs modifs sur la bannière en attendant

**Comment by clementWedodata** [comment]
Je vous propose qu'on affiche par défaut le texte que Brice à fait ce matin à la place du texte général qui n'apporte rien. Autant afficher directement ce qu'on fait avec les cookies. 
La question étant : 
- affiche t'on 2 boutons "accepter" + "refuser"
- si on affiche refuser, annuler le tracking des analytics et le store des cartes (possible ?) > dans ce cas, que ce passe t-il avec le bouton "fav" sur une carte ? 

cc @briceterdjman

**Comment by JulienParis** [comment]
en attente de + d'infos j'ai fait les modifs correspondantes à l'écran de Clément plus haut

**Comment by clementWedodata** [comment]
@JulienParis 

ok, donc voici les reco pour ce banner de cookie. On remplace tout le contenu du banner par > 
En français : 
**En poursuivant votre navigation, vous acceptez l’utilisation de cookies de navigation et de mesure d’audience
**

en Anglais : 
**By continuing your navigation, you agree to the use of cookies for navigation and audience measurement**

Avec un bouton "OK, j'ai compris"

<img width="730" alt="recettage-afd-playwithtransition-13" src="https://user-images.githubusercontent.com/52534300/64003355-68372000-cb0c-11e9-82df-3d44dafa8deb.png">

**Comment by JulienParis** [comment]
changé mais sur la base de la bannière précédente ( 1 ligne avec texte et bouton alignés )

**Comment by clementWedodata** [comment]
Ok, merci
