### ISSUE TITLE
[Bug] pendant l'animation lottie

### ISSUE THREAD

**Issue by clementWedodata** [we-do-data/IFS_AFD-ACES-dev#43]
@JulienParis 
C'est un nouveau bug, j'ai un gros bloc blanc en background du html pendant l'animation lottie. 
cf. screenshot vidéo > https://www.dropbox.com/s/jxvt2bncqe83m51/recettage-afd-playwithtransition-14.mov?dl=0

**Comment by JulienParis** [comment]
@clementWedodata j'ai fait une modif (sur quel navigateur tu étais ? Chrome ? J'ai testé sur Safari et Firefox et ça a l'air de rouler)

**Comment by clementWedodata** [comment]
@JulienParis 

merci, ça semble bon. J'avais le problème sur Chrome, Safari et FF.
