### ISSUE TITLE
add animation Lottie

### ISSUE THREAD

**Issue by JulienParis** [we-do-data/IFS_AFD-ACES-dev#7]

**Comment by JulienParis** [comment]
anim ajoutée... @clementWedodata pour check

**Comment by clementWedodata** [comment]
Merci @JulienParis  
L'animation dure 8s à 30fps. Il faudrait la laisser tourner jusqu'au bout si possible. 
;)

**Comment by JulienParis** [comment]
ok, j'ai mis 8s de délai auto avant de passer à la page suivante

**Comment by clementWedodata** [comment]
@JulienParis  

Ok, nickel. 
Pour finaliser la transition entre l'animation Lottie et l'écran suivant, est-il possible de : 
- faire apparaître le contenu de la page en fade in (opacité 0 > 1) ?
- faire apparaître le bandeau de cookie avec une transition du bas vers le haut, comme un tiroir qui s'ouvre ?

Ca éviterai l'effet bloc qui apparaît d'un coup.

**Comment by JulienParis** [comment]
@clementWedodata pour l'animation du bandeau on pourra faire une autre issue. J'ai ajouté différentes transitions entre les pages... Comme les transitions étaient pas mappées dès le départ j'ai un peu du bidouiller entre les pages (routes) et les layouts (qui s'appliquent sur plusieurs pages)...

**Comment by JulienParis** [comment]
@clementWedodata pe pas besoin de faire une nouvelle issue pour l'anim du bandeau je l'ai ajoutée. Pour check quoi...

**Comment by clementWedodata** [comment]
OK, les transitions entre les pages me vont et l'animation du bandeau aussi. Même si initialement j'avais parlé de l'animation quand il "entre en scène". Tu règles le soucis avec un fade in général, donc ça ve me va. Thanks
