### ISSUE TITLE
fix card scaling when clicking on `next`

### ISSUE THREAD

**Issue by JulienParis** [we-do-data/IFS_AFD-ACES-dev#9]

**Comment by clementWedodata** [comment]
J'en profite pour compléter ce ticket. On a encore un petit soucis de ratio quand tu scale la carte. J'ai l'impression que la card du dessous n'a pas le même ratio que celle qui va passer au premier plan. Ca créer un effet élastique pas vraiment souhaitable.

**Comment by JulienParis** [comment]
tentative de conservation du ratio par ce commit : https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/7af16d43e356519db8a04b242c5d60409d013a66

ya du mieux mais il reste encore une sorte d'effet élastique

**Comment by JulienParis** [comment]
refix ici : https://github.com/we-do-data/IFS_AFD-ACES-dev/commit/e945ccdd8eb8dbd4fd84062958dc4815900e0277

**Comment by JulienParis** [comment]
@clementWedodata changé effet lors du click sur bouton "next" : pas de scale, simple translation en diagonale

**Comment by clementWedodata** [comment]
@JulienParis 
merci pour la mise en place. En le voyant et à titre perso je ne suis pas convaincu du rendu de ce positionnement des cards. @briceterdjman pourra donner son avis, mais je vous propose 2 choses en alternatives, que voici en PJ. 
<img width="1056" alt="recettage-afd-playwithtransition-09" src="https://user-images.githubusercontent.com/52534300/63871589-6eb68200-c9bc-11e9-99f9-5c0ad0d5a4ec.png">

**Comment by JulienParis** [comment]
@clementWedodata j'attends que @briceterdjman dise ce qu'il en pense avant et ça devrait être un fix rapide

**Comment by JulienParis** [comment]
@clementWedodata pour passer le temps j'ai fait un test en mode "shuffle" et ça me semble marrant

**Comment by clementWedodata** [comment]
@JulienParis 

la proposition me va, je trouve ça mieux que l'effet d'escalier.
